---
deployment:
  tasks:
    - export DEPLOYPART=/home/u5587213/public_html/sisolusi.id/MPH_traking/
    - /bin/cp -R application $DEPLOYPART
    - /bin/cp -R assets $DEPLOYPART
    - /bin/cp -R system $DEPLOYPART
    - /bin/cp -R templog $DEPLOYPART
    - /bin/cp -R .htaccess $DEPLOYPART
    - /bin/cp -R composer.json $DEPLOYPART
    - /bin/cp -R index.php $DEPLOYPART
    - /bin/cp -R user_database.txt $DEPLOYPART
