---
deployment:
  tasks:
    - export DEPLOYPART=/home/u5587213/public_html/sisolusi.id/MPH_traking/
    - /bin/cp -R application $DEPLOYPART
    - /bin/cp -R assets $DEPLOYPART
    - /bin/cp -R system $DEPLOYPART
    - /bin/cp -R templog $DEPLOYPART
    - /bin/cp -R .editorconfig $DEPLOYPART
    - /bin/cp -R .gitignore $DEPLOYPART
    - /bin/cp -R .htaccess $DEPLOYPART


